#!/bin/bash
set -euo pipefail

### NOTES ###
# Builds PGlite as a standalone WASM module that runs on any WASI runtime
# (Wasmtime, Node's node:wasi, ...) without the emscripten JS glue.
# See the "Standalone build" section of README-PGLITE-DEV.md.
#
# Differences from build-pglite.sh:
#   - out-of-tree build in $BUILD_DIR, so the source tree stays clean
#   - native wasm exception handling for setjmp/longjmp (exnref encoding)
#   - WASMFS in-memory filesystem; share/ data ships as a tarball the host loads at startup
#   - no dynamic linking: extensions are linked into the module ($STATIC_LIBRARIES)
#   - host I/O through the "pglite" import module (see pglite/src/pglitec/pglitec_standalone.c)
#
# $INSTALL_PREFIX is expected to point to the installation folder of various libraries built to wasm (see pglite-builder)
#############

SRC_DIR=$(pwd)
BUILD_DIR=${BUILD_DIR:-"$SRC_DIR/build/standalone"}
# final output folder
INSTALL_FOLDER=${INSTALL_FOLDER:-"/pglite/standalone"}

if [ -f "$SRC_DIR/config.status" ]; then
    echo "error: $SRC_DIR has been configured in-tree (probably by build-pglite.sh)."
    echo "The standalone build is an out-of-tree build and needs a clean source tree:"
    echo "run it from a separate checkout (e.g. 'git worktree add'), or 'make distclean' first."
    exit 1
fi

PGLITE_CFLAGS="-sWASM_BIGINT -sSUPPORT_LONGJMP=wasm -sWASM_EXNREF=1 -DPGLITE_STANDALONE -Wno-declaration-after-statement -Wno-macro-redefined -Wno-unused-function -Wno-missing-prototypes -Wno-incompatible-pointer-types"
if [ "${DEBUG:-false}" = true ]
then
    echo "pglite: building debug version of standalone module."
    PGLITE_CFLAGS="$PGLITE_CFLAGS -g"
else
    echo "pglite: building release version of standalone module."
    PGLITE_CFLAGS="$PGLITE_CFLAGS -O2"
    unset DEBUG
fi

mkdir -p "$BUILD_DIR"

# first build pglite-libc objects WITHOUT the overriding flags
emcc $PGLITE_CFLAGS -c "$SRC_DIR/pglite/src/pglitec/pglitec.c" -o "$BUILD_DIR/pglitec.o"
emcc $PGLITE_CFLAGS -c "$SRC_DIR/pglite/src/pglitec/pglitec_standalone.c" -o "$BUILD_DIR/pglitec_standalone.o"

PGLITE_CFLAGS="$PGLITE_CFLAGS \
-D__PGLITE__ \
-Dsystem=pgl_system -Dpopen=pgl_popen -Dpclose=pgl_pclose \
-Dgeteuid=pgl_geteuid -Dgetuid=pgl_getuid -Dgetpwuid=pgl_getpwuid \
-Dexit=pgl_exit \
-Dmunmap=pgl_munmap \
-Dfcntl=pgl_fcntl \
-Datexit=pgl_atexit \
-Dsetsockopt=pgl_setsockopt -Dgetsockopt=pgl_getsockopt -Dgetsockname=pgl_getsockname \
-Drecv=pgl_recv -Dsend=pgl_send -Dconnect=pgl_connect \
-Dpoll=pgl_poll \
-Dshmget=pgl_shmget -Dshmat=pgl_shmat -Dshmdt=pgl_shmdt -Dshmctl=pgl_shmctl \
-Dlongjmp=pgl_longjmp -Dsiglongjmp=pgl_siglongjmp"

echo "pglite: PGLITE_CFLAGS=$PGLITE_CFLAGS"

PGLITE_LDFLAGS="-sWASM_BIGINT -sUSE_PTHREADS=0 -sSUPPORT_LONGJMP=wasm -sWASM_EXNREF=1"
# `make` still builds the frontend programs (initdb, psql, ...) for the JS runtime; only initdb is relinked (step 3.1)
PGLITE_LDFLAGS_EX="-sERROR_ON_UNDEFINED_SYMBOLS=0 -sALLOW_MEMORY_GROWTH $BUILD_DIR/pglitec.o $BUILD_DIR/pglitec_standalone.o"

CONFIGURE_PARAMS="\
ac_cv_exeext=.js \
--host wasm32-unknown-emscripten \
--disable-spinlocks \
--without-llvm  \
--without-pam \
--disable-largefile \
--with-openssl=no \
--without-readline \
--with-icu \
--with-includes=$INSTALL_PREFIX/include:$INSTALL_PREFIX/include/libxml2 \
--with-libraries=$INSTALL_PREFIX/lib \
--with-uuid=ossp \
--with-zlib \
--with-libxml \
--with-libxslt \
--with-template=emscripten \
--prefix=$INSTALL_FOLDER"

cd "$BUILD_DIR"

# Step 1: configure, if never done or this script changed since
if [ ! -f config.status ] || [ "$SRC_DIR/build-pglite-standalone.sh" -nt config.status ]; then
    LDFLAGS=$PGLITE_LDFLAGS \
    LDFLAGS_EX=$PGLITE_LDFLAGS_EX \
    ICU_CFLAGS="-I/install/libs/include" \
    ICU_LIBS="-L/install/libs/lib -licui18n -licuuc -licudata" \
    CFLAGS=${PGLITE_CFLAGS} emconfigure "$SRC_DIR/configure" $CONFIGURE_PARAMS || { echo 'error: emconfigure failed' ; exit 11; }
fi

# Step 2: make and install core
emmake make PORTNAME=emscripten -j || { echo 'error: emmake make PORTNAME=emscripten -j' ; exit 21; }
emmake make PORTNAME=emscripten install || { echo 'error: emmake make PORTNAME=emscripten install' ; exit 23; }

# Step 2.1: extensions with a library, as "name:directory". There is no dynamic
# loading, so they are linked into the module (see pglitec_standalone.h).
# initdb needs dict_snowball and plpgsql.
STATIC_LIBRARIES="dict_snowball:src/backend/snowball plpgsql:src/pl/plpgsql/src ltree:contrib/ltree btree_gist:contrib/btree_gist"
LLVM_NM="$(dirname "$(command -v emcc)")/../bin/llvm-nm"
STATIC_OBJS=""
STATIC_TABLE="$BUILD_DIR/pgl_static_libraries.c"
{
    echo "/* generated by build-pglite-standalone.sh */"
    echo '#include "postgres.h"'
    echo '#include "fmgr.h"'
    echo '#include "pglitec_standalone.h"'
} > "$STATIC_TABLE"
STATIC_ENTRIES=""
for entry in $STATIC_LIBRARIES; do
    name=${entry%%:*}
    dir=${entry#*:}
    # recompile for static linking (no -fPIC), with the functions every module defines renamed
    emmake make PORTNAME=emscripten -C "$dir" clean
    emmake make PORTNAME=emscripten -C "$dir" CFLAGS_SL= \
        COPT="-DPg_magic_func=pgl_${name}_Pg_magic_func -D_PG_init=pgl_${name}__PG_init" \
        || { echo "error: emmake make PORTNAME=emscripten -C $dir" ; exit 25; }
    # the control and SQL files, for contrib modules
    emmake make PORTNAME=emscripten -C "$dir" install || { echo "error: emmake make PORTNAME=emscripten -C $dir install" ; exit 25; }
    objs=$(find "$BUILD_DIR/$dir" -name '*.o' | sort | tr '\n' ' ')
    STATIC_OBJS="$STATIC_OBJS $objs"
    funcs=$("$LLVM_NM" --defined-only --extern-only $objs | awk '$2 == "T" {print $3}' | sort -u)
    # what dfmgr.c looks up: the module magic, _PG_init, and the V1 functions (those
    # with pg_finfo_*; some modules declare info for functions they don't define)
    v1_funcs=$(echo "$funcs" | sed -n 's/^pg_finfo_//p' | grep -Fxf <(echo "$funcs") || true)
    {
        echo "extern const Pg_magic_struct *pgl_${name}_Pg_magic_func(void);"
        if echo "$funcs" | grep -qx "pgl_${name}__PG_init"; then
            echo "extern void pgl_${name}__PG_init(void);"
        fi
        for f in $v1_funcs; do
            echo "extern const Pg_finfo_record *pg_finfo_$f(void);"
            echo "extern Datum $f(PG_FUNCTION_ARGS);"
        done
        echo "static const pgl_static_symbol ${name}_symbols[] = {"
        echo "    {\"Pg_magic_func\", (void *) pgl_${name}_Pg_magic_func},"
        if echo "$funcs" | grep -qx "pgl_${name}__PG_init"; then
            echo "    {\"_PG_init\", (void *) pgl_${name}__PG_init},"
        fi
        for f in $v1_funcs; do
            echo "    {\"pg_finfo_$f\", (void *) pg_finfo_$f},"
            echo "    {\"$f\", (void *) $f},"
        done
        echo "    {NULL, NULL}"
        echo "};"
    } >> "$STATIC_TABLE"
    STATIC_ENTRIES="$STATIC_ENTRIES    {\"$name\", ${name}_symbols},\n"
done
printf "const pgl_static_library pgl_static_libraries[] = {\n${STATIC_ENTRIES}    {NULL, NULL}\n};\n" >> "$STATIC_TABLE"
emcc $PGLITE_CFLAGS -I"$BUILD_DIR/src/include" -I"$SRC_DIR/src/include" -I"$SRC_DIR/pglite/src/pglitec" \
    -c "$STATIC_TABLE" -o "$BUILD_DIR/pgl_static_libraries.o" || { echo 'error: compiling the extension table' ; exit 26; }

# Step 2.2: extensions without a library (SQL only), from pglite/other_extensions.
# Built from a copy, so the source tree stays clean, against this build tree
# rather than PGXS. Their makefiles only ask pg_config for the version.
SQL_EXTENSIONS="pgtap"
PG_VERSION=$(sed -n 's/^#define PG_VERSION "\(.*\)"$/\1/p' src/include/pg_config.h)
printf '#!/bin/sh\necho "PostgreSQL %s"\n' "$PG_VERSION" > "$BUILD_DIR/pg_config-version"
chmod +x "$BUILD_DIR/pg_config-version"
for name in $SQL_EXTENSIONS; do
    src="$SRC_DIR/pglite/other_extensions/$name"
    if [ ! -f "$src/Makefile" ]; then
        echo "error: $src is missing: git submodule update --init pglite/other_extensions/$name"
        exit 27
    fi
    rm -rf "$BUILD_DIR/other_extensions/$name"
    mkdir -p "$BUILD_DIR/other_extensions"
    cp -r "$src" "$BUILD_DIR/other_extensions/$name"
    emmake make PORTNAME=emscripten -C "$BUILD_DIR/other_extensions/$name" \
        NO_PGXS=1 NO_GENERATED_HEADERS=1 top_builddir="$BUILD_DIR" srcdir="$BUILD_DIR/other_extensions/$name" \
        PG_CONFIG="$BUILD_DIR/pg_config-version" install \
        || { echo "error: building $name" ; exit 27; }
done

# Step 3: link the standalone module
# Functions the host calls, in addition to the EMSCRIPTEN_KEEPALIVE ones in pglitec*.c
STANDALONE_EXPORTS="_malloc,_free,_pgl_setPGliteActive,\
_PostgresMainLoopOnce,_PostgresMainLongJmp,_PostgresSendReadyForQueryIfNecessary,\
_pq_buffer_remaining_data,_ProcessStartupPacket,\
_pgl_startPGlite,_pgl_getMyProcPort,_pgl_sendConnData,_pgl_pq_flush"

STANDALONE_LDFLAGS="\
-sSTANDALONE_WASM=1 --no-entry \
-sWASMFS=1 \
-sWASM_BIGINT \
-sSUPPORT_LONGJMP=wasm -sWASM_EXNREF=1 \
-sSTACK_SIZE=8MB \
-sINITIAL_MEMORY=128MB \
-sALLOW_MEMORY_GROWTH \
-sERROR_ON_UNDEFINED_SYMBOLS=1 \
-sEXPORTED_FUNCTIONS=$STANDALONE_EXPORTS"

# the pglitec objects are linked in through LDFLAGS_EX; they are not make prerequisites, so always relink
rm -f src/backend/pglite.wasm
# LDFLAGS_EX_BE (--export-dynamic) would export every symbol, which only dynamically loaded extensions need
POSTGRES_PGLITE_FLAGS="$PGLITE_CFLAGS $STANDALONE_LDFLAGS $STATIC_OBJS $BUILD_DIR/pgl_static_libraries.o" \
    emmake make PORTNAME=emscripten -C src/backend/ pglite X=.wasm LDFLAGS_EX_BE= || { echo 'error: emmake make PORTNAME=emscripten -C src/backend/ pglite' ; exit 31; }

# Step 3.1: link initdb as a standalone module too, for hosts to create PGDATA.
# It runs postgres through the host (see "Subprocesses" in pglitec_standalone.c)
INITDB_LDFLAGS="\
-sSTANDALONE_WASM=1 --no-entry \
-sWASMFS=1 \
-sALLOW_MEMORY_GROWTH \
-sERROR_ON_UNDEFINED_SYMBOLS=1 \
-sEXPORTED_FUNCTIONS=_malloc,_free \
$BUILD_DIR/pglitec.o $BUILD_DIR/pglitec_standalone.o"
emmake make PORTNAME=emscripten -C src/bin/initdb initdb X=-standalone.wasm LDFLAGS_EX="$INITDB_LDFLAGS" || { echo 'error: emmake make PORTNAME=emscripten -C src/bin/initdb initdb' ; exit 32; }

# Step 4: the runtime filesystem (share/ data, ICU, static files), which the
# host unpacks into the module's in-memory filesystem before startup
FS_STAGING="$BUILD_DIR/fs-staging"
rm -rf "$FS_STAGING"
mkdir -p "$FS_STAGING/pglite/bin" "$FS_STAGING/pglite/share" "$FS_STAGING/home/postgres" "$FS_STAGING/tmp"
cp "$SRC_DIR/pglite/static/PGPASSFILE" "$FS_STAGING/home/postgres/.pgpass"
# postgres locates its share/ dir relative to its own executable, which must exist
cp "$SRC_DIR/pglite/static/empty" "$FS_STAGING/pglite/bin/initdb"
cp "$SRC_DIR/pglite/static/empty" "$FS_STAGING/pglite/bin/postgres"
chmod 755 "$FS_STAGING/pglite/bin/"*
# the extensions linked into the module: dfmgr.c checks that the file exists
mkdir -p "$FS_STAGING/pglite/lib/postgresql"
for entry in $STATIC_LIBRARIES; do
    cp "$SRC_DIR/pglite/static/empty" "$FS_STAGING/pglite/lib/postgresql/${entry%%:*}.so"
done
cp -r "$INSTALL_FOLDER/share/postgresql" "$FS_STAGING/pglite/share/postgresql"
cp "$SRC_DIR/pglite/static/password" "$FS_STAGING/pglite/password"
cp "$SRC_DIR/pglite/static/locale-a" "$FS_STAGING/pglite/locale-a"
cp -r "$SRC_DIR/pglite/static/minimal-icu/76.1" "$FS_STAGING/pglite/icu"

mkdir -p "$INSTALL_FOLDER/bin"
cp src/backend/pglite.wasm "$INSTALL_FOLDER/bin/pglite-standalone.wasm"
cp src/bin/initdb/initdb-standalone.wasm "$INSTALL_FOLDER/bin/initdb-standalone.wasm"
tar -C "$FS_STAGING" -czf "$INSTALL_FOLDER/bin/pglite-standalone-fs.tar.gz" .
echo "pglite: built pglite-standalone.wasm, initdb-standalone.wasm and pglite-standalone-fs.tar.gz in $INSTALL_FOLDER/bin"
